version: "3"

services:
    s_nginx:
        image: nginx:latest
        container_name: btx_ngx
        volumes:
            - ./:/var/www/html:cached
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        ports:
            - "82:80"
        depends_on:
            - s_php

    s_php:
        build:
            context: docker/php
            args:
                TIMEZONE: Europe/Moscow
        container_name: btx_php_v3
        volumes:
            - ./:/var/www/html:cached
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini:cached
            - ./docker/php/php-fpm.conf:/usr/local/etc/php-fpm.d/99-custom.conf:cached

    s_mysql:
        image: "mysql:8.4.3"
        container_name: btx_db
        volumes:
            - ./db/mysql:/var/lib/mysql
        environment:
               MYSQL_ROOT_PASSWORD: root
               MYSQL_DATABASE: btxdb
               MYSQL_USER: local
               MYSQL_PASSWORD: local
        ports:
            - "3306:3306"
